require:
  - standard/cop/block_single_line_braces
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'tmp/**/*'
    - '.github/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 2.7

Standard/BlockSingleLineBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

RSpec/FilePath:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
