module Imgproxy
  OPTIONS_ALIASES = {
    resize: :rs,
    size: :s,
    resizing_type: :rt,
    width: :w,
    height: :h,
    enlarge: :en,
    extend: :ex,
    gravity: :g,
    crop: :c,
    padding: :pd,
    trim: :t,
    quality: :q,
    max_bytes: :mb,
    background: :bg,
    adjust: :a,
    brightness: :br,
    contrast: :co,
    saturation: :sa,
    blur: :bl,
    sharpen: :sh,
    pixelate: :pix,
    watermark: :wm,
    watermark_url: :wmu,
    style: :st,
    preset: :pr,
    cachebuster: :cb,
    video_thumbnail_second: :vts,
    filename: :fn,
  }.freeze
end
