#
# This action is triggered by the repository_dispatch event
# published by the imgproxy/imgproxy-docs repository.
# It creates an issue and assign it to the gem's maintainers.
#
---
name: Create an issue about updated imgproxy docs
on:
  repository_dispatch:
    types:
      - imgproxy-usage-updated

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Create an issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/templates/ISSUE.md
